# Generated by Django 2.2.13 on 2020-10-24 09:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='автор', to=settings.AUTH_USER_MODEL, verbose_name='Избранное'),
        ),
    ]
